### ISSUE TITLE
Explain HowTo Use The Package

### ISSUE THREAD

**Issue by umutphp** [eyupinann/quote#1]
Can you please how to use the package? How can I install your package to a Laravel Application.

**Comment by eyupinann** [comment]
Ok thank you for your suggestion i am adding readme you can check it there

**Comment by umutphp** [comment]
Hi @eyupinann ,

Can you please add a sample usage to the Usage section of the README? I could not understand how to use your package in my Laravel App.

**Comment by eyupinann** [comment]
Hello, I added the readme, you can check it there.

**Comment by umutphp** [comment]
``@eyupinann 

What is this? Is this a controller action? Can you please explain how your package should be used?
```
use eyupinann\Quote\Index;

public function App(Index $index) {
  return $index->page('Contact',['test@test.com','0505'])
}
```

**Comment by eyupinann** [comment]
Using this function, we send the page name and content to the relevant function and return it.

**Comment by umutphp** [comment]
Lets make a quick session, If you are available now.

**Comment by eyupinann** [comment]
Yes
